# Generated by Django 2.2.6 on 2019-11-16 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ca', '0007_auto_20191112_0119'),
        ('main_page', '0004_auto_20191112_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='ca_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ca.Profile', verbose_name='CA Code'),
        ),
    ]
