# Generated by Django 2.2.6 on 2019-11-17 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0006_participant_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='participant_code',
            field=models.CharField(max_length=11, unique=True, verbose_name='Participant Code'),
        ),
    ]
