# Generated by Django 2.2.6 on 2019-12-03 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0008_auto_20191203_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='category',
            field=models.CharField(choices=[('1', 'Aeromodelling'), ('7', 'Astronomy'), ('5', 'Automotive'), ('6', 'CAD'), ('3', 'Coding'), ('10', 'Entrepreneurship'), ('2', 'Finance'), ('8', 'Gaming'), ('11', 'Photo Editing'), ('4', 'Robotics'), ('9', 'Quizzing'), ('12', 'Departmental Events')], max_length=20),
        ),
    ]
