# Generated by Django 2.2.6 on 2019-12-21 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_page', '0011_workshop'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechConnect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Your Name', max_length=100)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='IN', verbose_name='Contact Number')),
                ('designation', models.CharField(choices=[('s', 'Student'), ('f', 'Faculty Member'), ('o', 'Other')], max_length=2)),
                ('campus_name', models.CharField(default='Campus Name', max_length=100)),
                ('city', models.CharField(default='City', max_length=100)),
                ('state', models.CharField(default='State', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
