# Generated by Django 2.2.6 on 2019-12-21 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0012_techconnect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Your Name'),
        ),
        migrations.DeleteModel(
            name='TechConnect',
        ),
    ]
