# Generated by Django 2.2.6 on 2019-12-24 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0013_auto_20191221_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='city_name',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='college_name',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='user',
        ),
        migrations.AddField(
            model_name='workshop',
            name='fees',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='WorkshopRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_request_id', models.CharField(default='none', max_length=100)),
                ('transaction_id', models.CharField(default='none', max_length=100)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.Participant')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.Workshop')),
            ],
        ),
    ]
