# Generated by Django 2.2.6 on 2019-12-25 12:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0016_workshopaccomodation'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshopaccomodation',
            name='payment_request_id',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='workshopaccomodation',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workshopaccomodation',
            name='transaction_id',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
