# Generated by Django 2.2.6 on 2019-12-26 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0019_auto_20191225_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='rulebook',
            field=models.URLField(blank=True),
        ),
    ]
