# Generated by Django 2.2.6 on 2019-12-27 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0020_workshop_rulebook'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='workshop_type',
            field=models.CharField(choices=[('t', 'Technical'), ('m', 'Management')], default='t', max_length=2),
            preserve_default=False,
        ),
    ]
