# Generated by Django 2.2.6 on 2019-12-27 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0022_auto_20191227_0721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='workshop_type',
            field=models.CharField(choices=[('t', 'Technical'), ('m', 'Management'), ('c', 'Career Training')], max_length=2),
        ),
    ]
