# Generated by Django 2.2.6 on 2020-01-05 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0024_participant_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='prize',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
    ]
