# Generated by Django 2.2.6 on 2020-01-06 14:56

from django.db import migrations, models
import main_page.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0025_auto_20200105_1326'),
    ]

    operations = [
        migrations.CreateModel(
            name='Talk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to=main_page.models.get_file_path)),
                ('venue', models.CharField(max_length=100)),
                ('start_date_time', models.DateTimeField()),
                ('para1', models.TextField(blank=True, null=True)),
                ('para2', models.TextField(blank=True, null=True)),
                ('show', models.BooleanField(default=True)),
            ],
        ),
    ]
