# Generated by Django 2.2.6 on 2020-01-09 20:58

from django.db import migrations, models
import main_page.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0026_talk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=main_page.models.get_file_path_talk),
        ),
    ]
