# Generated by Django 2.2.6 on 2020-01-15 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0027_auto_20200109_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregistration',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='workshopaccomodation',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='workshopregistration',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
