# Generated by Django 2.2.6 on 2020-01-17 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0029_payment_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='talk',
            name='para3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='talk',
            name='para4',
            field=models.TextField(blank=True, null=True),
        ),
    ]
