# Generated by Django 2.2.6 on 2020-01-24 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0033_paymentpaid_seoworkshoppaidregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='talk',
            name='link',
            field=models.CharField(default='Google_Form_Link', max_length=150),
        ),
        migrations.AddField(
            model_name='talk',
            name='show_link',
            field=models.BooleanField(default=False),
        ),
    ]
