# Generated by Django 2.2.6 on 2020-02-01 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0034_auto_20200125_0325'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SEOWorkshopPaidRegistration',
        ),
        migrations.AddField(
            model_name='workshop',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
