# Generated by Django 2.2.6 on 2020-02-01 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0035_auto_20200201_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinator',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_page.Participant'),
        ),
    ]
