# Generated by Django 2.2.6 on 2020-02-03 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0036_coordinator_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
