# Generated by Django 2.2.6 on 2019-12-29 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import techconnect.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('techconnect', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Centers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100, verbose_name='City')),
                ('city_image', models.ImageField(blank=True, null=True, upload_to=techconnect.models.get_file_path)),
                ('college_name', models.CharField(max_length=100, verbose_name='College Name')),
                ('college_image', models.ImageField(blank=True, null=True, upload_to=techconnect.models.get_file_path)),
                ('state', models.CharField(max_length=100, verbose_name='State')),
            ],
        ),
        migrations.CreateModel(
            name='TechconnectParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Your Name', max_length=100)),
                ('phone_number', models.CharField(default=None, max_length=10)),
                ('college_name', models.CharField(default='no college', max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Workshops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workshop_name', models.CharField(max_length=100, verbose_name='Workshop')),
                ('fees', models.IntegerField(default=1000)),
                ('rulebook', models.URLField(blank=True)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='techconnect.Centers')),
            ],
        ),
        migrations.CreateModel(
            name='WorkshopRegistrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_request_id', models.CharField(default='none', max_length=100)),
                ('transaction_id', models.CharField(default='none', max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='techconnect.TechconnectParticipant')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='techconnect.Workshops')),
            ],
        ),
    ]
