# Generated by Django 2.2.6 on 2020-01-24 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techconnect', '0003_auto_20191230_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshops',
            name='dates',
            field=models.CharField(default='21st & 22nd March', max_length=100, verbose_name='Dates'),
        ),
    ]
