# Generated by Django 2.2.6 on 2020-01-13 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accomodation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
