# Generated by Django 2.2.6 on 2020-02-05 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0037_events_closed'),
        ('accomodation', '0003_auto_20200113_1915'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_on_7th', models.CharField(default='none', max_length=3)),
                ('meal_on_8th', models.CharField(default='none', max_length=3)),
                ('meal_on_9th', models.CharField(default='none', max_length=3)),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_page.Participant')),
            ],
        ),
    ]
