# Generated by Django 2.2.6 on 2020-02-05 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accomodation', '0004_meal'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccommodationDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accomodation_on_7th', models.BooleanField(default=False)),
                ('accomodation_on_8th', models.BooleanField(default=False)),
                ('accomodation_on_9th', models.BooleanField(default=False)),
                ('accommodation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accomodation.Accommodation')),
            ],
        ),
    ]
