# Generated by Django 2.2.6 on 2020-01-20 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0032_auto_20200119_2214'),
        ('startup_conclave', '0003_paymentforstalls'),
    ]

    operations = [
        migrations.CreateModel(
            name='BootCampTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Team Name')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.Participant')),
            ],
        ),
        migrations.AddField(
            model_name='startupteam',
            name='commitment',
            field=models.CharField(blank=True, choices=[('1', 'Full Time'), ('2', 'Part Time')], max_length=30, null=True, verbose_name='Commitment'),
        ),
        migrations.AddField(
            model_name='startupteam',
            name='founder_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Founder Name'),
        ),
        migrations.AddField(
            model_name='startupteam',
            name='founder_phone_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Founder Phone Number'),
        ),
        migrations.AddField(
            model_name='startupteam',
            name='requirements',
            field=models.CharField(blank=True, choices=[('1', 'Investor/Banks'), ('2', 'IPR Company'), ('3', 'Company Incorporation'), ('4', 'Web & App Development Company'), ('5', 'Manufacturing Company'), ('6', 'Marketing Company')], max_length=40, null=True, verbose_name='Requirements of your Startup'),
        ),
        migrations.AddField(
            model_name='startupteam',
            name='sector',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sector'),
        ),
        migrations.AddField(
            model_name='startupteam',
            name='startup_category',
            field=models.CharField(choices=[('1', 'Operational'), ('2', 'Operational > 1 year'), ('3', 'Idea'), ('4', 'Concept'), ('5', 'Proof of Concept'), ('6', 'Pilot')], default='1', max_length=30, verbose_name='Startup Category'),
        ),
        migrations.AddField(
            model_name='startupteam',
            name='startup_name',
            field=models.CharField(default='Startup Name', max_length=100, verbose_name='Startup Name'),
        ),
        migrations.AddField(
            model_name='startupteam',
            name='why_invest',
            field=models.TextField(blank=True, null=True, verbose_name='Tell Investor- Why invest in you?'),
        ),
        migrations.CreateModel(
            name='BootCampTeamHasMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.Participant')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startup_conclave.BootCampTeam')),
            ],
        ),
    ]
