# Generated by Django 2.2.6 on 2020-01-20 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('startup_conclave', '0004_auto_20200120_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='startupregistrations',
            name='startup_name',
            field=models.ForeignKey(default='4', on_delete=django.db.models.deletion.CASCADE, to='startup_conclave.StartupTeam'),
            preserve_default=False,
        ),
    ]
