# Generated by Django 2.2.6 on 2020-01-20 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('startup_conclave', '0005_startupregistrations_startup_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequirementChoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=40)),
            ],
        ),
        migrations.RemoveField(
            model_name='startupteam',
            name='requirements',
        ),
        migrations.AlterField(
            model_name='startupteam',
            name='sector',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sector in which your startup belongs (Hardware/Software/Food/Agriculture/Technology etc.)'),
        ),
        migrations.AlterField(
            model_name='startupteam',
            name='startup_category',
            field=models.CharField(choices=[('1', 'Operational'), ('2', 'Operational > 1 year'), ('3', 'Idea'), ('4', 'Concept'), ('5', 'Proof of Concept'), ('6', 'Pilot')], default='1', max_length=30, verbose_name='Stage of your Startup'),
        ),
        migrations.CreateModel(
            name='StartupTeamHasRequirements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startup_conclave.RequirementChoices')),
                ('startup_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startup_conclave.StartupTeam')),
            ],
        ),
        migrations.AddField(
            model_name='startupteam',
            name='requirements',
            field=models.ManyToManyField(through='startup_conclave.StartupTeamHasRequirements', to='startup_conclave.RequirementChoices'),
        ),
    ]
