# Generated by Django 2.2.6 on 2020-01-21 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0032_auto_20200119_2214'),
        ('startup_conclave', '0006_auto_20200120_1841'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayForStalls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_request_id', models.CharField(default='none', max_length=100)),
                ('transaction_id', models.CharField(default='none', max_length=100)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegisterForStalls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startup_name', models.CharField(default='Startup Name', max_length=100, verbose_name='Startup Name')),
                ('founder_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Founder Name')),
                ('founder_phone_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Founder Phone Number')),
                ('number', models.PositiveSmallIntegerField(verbose_name='No. of people representing the startup')),
                ('about', models.TextField(blank=True, null=True, verbose_name='About Your Startup')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.Participant')),
            ],
        ),
        migrations.DeleteModel(
            name='PaymentForStalls',
        ),
        migrations.AddField(
            model_name='payforstalls',
            name='stall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startup_conclave.RegisterForStalls'),
        ),
    ]
