# Generated by Django 2.2.6 on 2020-01-23 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup_conclave', '0007_auto_20200121_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='bootcampteam',
            name='description',
            field=models.TextField(default='No Description', verbose_name='Brief Description about your idea'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bootcampteam',
            name='startup_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Startup Name(If applicable)'),
        ),
    ]
