# Generated by Django 2.2.6 on 2020-01-23 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup_conclave', '0008_auto_20200124_0211'),
    ]

    operations = [
        migrations.AddField(
            model_name='startupteam',
            name='cin_no',
            field=models.CharField(default='initial registrations without cin', max_length=22, verbose_name='Corporate Identification Number (CIN Number)'),
            preserve_default=False,
        ),
    ]
