# Generated by Django 2.2.6 on 2020-01-23 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup_conclave', '0009_startupteam_cin_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startupteam',
            name='cin_no',
            field=models.CharField(max_length=21, verbose_name='Corporate Identification Number (CIN Number)'),
        ),
    ]
