# Generated by Django 2.2.6 on 2020-01-26 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0034_auto_20200125_0325'),
        ('startup_conclave', '0009_startupteam_cin_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerforstalls',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.Participant', verbose_name='Leader'),
        ),
        migrations.CreateModel(
            name='RegisterForStallsHasMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.Participant')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startup_conclave.RegisterForStalls')),
            ],
        ),
    ]
