# Generated by Django 2.2.6 on 2020-01-26 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup_conclave', '0010_auto_20200126_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerforstalls',
            name='stall_on_7th',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registerforstalls',
            name='stall_on_8th',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registerforstalls',
            name='stall_on_9th',
            field=models.BooleanField(default=False),
        ),
    ]
