# Generated by Django 2.1.2 on 2019-10-06 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ca', '0002_auto_20191006_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
