# Generated by Django 2.2.6 on 2019-10-20 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ca', '0002_remove_profile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='why_ca',
            field=models.CharField(default='hello', max_length=1500),
            preserve_default=False,
        ),
    ]
