# Generated by Django 2.1.2 on 2019-10-07 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ca', '0003_remove_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='college_name',
            field=models.CharField(max_length=150),
        ),
    ]
