# Generated by Django 2.2.6 on 2019-10-20 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ca', '0004_auto_20191020_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ca_code',
            field=models.CharField(default=None, max_length=6, unique=True, verbose_name='CA Code'),
            preserve_default=False,
        ),
    ]
