# Generated by Django 2.2.6 on 2019-11-03 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ca', '0005_profile_ca_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='your_name',
            field=models.CharField(default='Your Name', max_length=150),
        ),
    ]
