name: CI

on:
  push:
    branches: 
      - production

jobs:
  deploy:

    runs-on: ubuntu-18.04

    steps:
    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        passphrase: ${{ secrets.PASSPHRASE }}
        script: |
          source advitiya20env/bin/activate
          cd Advitiya-20/
          source .env
          python manage.py collectstatic | yes
